### ISSUE TITLE
make_recalls_matrix: np.squeeze error

### ISSUE THREAD

**Issue by Riley16** [pennmem/pybeh_pd#1]
https://github.com/pennmem/pybeh_pd/blob/5555d78e03b9010a26d2210e6a775731597787fc/pybeh_pd.py#L89

I'm getting an error with np.squeeze (numpy version 1.21.2) when I attempt to run the example code for the min_lag_crp in https://github.com/pennmem/pybeh_pd/blob/main/repFR1_analyses.ipynb. The code runs properly when I remove that line. From what I can tell, all versions of numpy.squeeze error out if the axes being squeezed are not None or don't have length 1: https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html) so I think this should always error out if max_n_reps != 1. The intended behavior is then to reduce the recalls array to be 2D instead of 3D for standard non-repeated word presentations? If so, we should add a check for max_n_reps == 1.

**Comment by dhalpern** [comment]
fixed in commit 36718c2b3c7fa77d49f452b9a7a2bd9379db6a19
